version: 2
jobs:
  build:
    docker:

      # Specify the version you desire here
      - image: circleci/php:7.4.2-fpm
      
    working_directory: ~/laravel

    steps:
      - checkout

      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install pdo_mysql

      - run: sudo composer self-update

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      
      - run:
          name: Create .env file
          command: |
              touch .env;
              echo DB_CONNECTION=$DB_CONNECTION >> .env;
              echo DB_HOST=$DB_HOST >> .env;
              echo DB_PORT=$DB_PORT >> .env;
              echo DB_DATABASE=$DB_DATABASE >> .env;
              echo DB_USERNAME=$DB_USERNAME >> .env;
              echo DB_PASSWORD=$DB_PASSWORD >> .env;

      - run:
          name: Setup Laravel stuffs
          command: |
            php artisan migrate --env=staging --force

      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  notify_deploy:
    jobs:
      - build:
          filters: 
            branches:
              only: master
              